# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    container_name: container-pg
    restart: always
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning #--requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
      
volumes:
  postgres-data:
  cache:
    driver: local  
    
    
    

  #pgadmin:
  #  container_name: container-pgadmin
  #  image: dpage/pgadmin4
  #  depends_on:
  #    - postgres
  #  ports:
  #    - "5050:80"
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #    PGADMIN_DEFAULT_PASSWORD: postgres
  #  restart: unless-stopped

 