name: Dependabot upgrade test

on:
  push:
    branches:
      - staging
      - my-staging
      - main
      - "dependabot/**"
  workflow_dispatch:    

jobs:
  dependabot-frontend-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Vue 2 install
        working-directory: ./frontend
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          npm install

      - name: Vue 2 build
        working-directory: ./frontend
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          npm run build --if-present

      - name: Vue 2 test
        working-directory: ./frontend
        run: |
          npm run test

      - name: Vue 3 build
        working-directory: ./
        env:
          ALLOWED_HOSTS: localhost
          REDIS_URL: redis://localhost:6379/0
          STATICFILES_STORAGE: django.contrib.staticfiles.storage.StaticFilesStorage
        run: |
          python3 manage.py collectstatic --noinput
          cd ./2024-frontend
          npm install
          npm run build --if-present
